'use client';

import { Gift } from 'lucide-react';

export function Referrals() {
  const currentVolume = 0;
  const targetVolume = 10000;
  const progressPercent = Math.min((currentVolume / targetVolume) * 100, 100);
  const remainingVolume = targetVolume - currentVolume;

  return (
    <div className="h-full overflow-y-auto bg-[#0f0f13] p-8 lg:p-12 flex text-[#f5f5f5]">
      <div className="max-w-6xl mx-auto w-full grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 items-start pt-6">
        
        {/* Left Section */}
        <div className="max-w-xl">
          <div className="flex items-center gap-3 mb-6">
            <Gift className="w-6 h-6 text-[#fa5b2a]" />
            <h1 className="text-2xl font-bold tracking-tight text-white">Refer users</h1>
          </div>

          <h2 className="text-5xl lg:text-[56px] font-bold text-[#fa5b2a] leading-[1.1] tracking-tight mb-10">
            Earn upto 70% fee share
          </h2>

          <div className="space-y-2 mb-8">
            <h3 className="text-[22px] font-semibold text-white leading-snug">
              Reach $10K in trading volume on HyperLiquid (via HyperSignals)
            </h3>
            <p className="text-gray-500 text-[17px]">
              to create a referral link
            </p>
          </div>

          <div className="space-y-4 mb-8">
            <div className="flex items-center gap-4">
              <div className="flex-1 bg-[#1a1a24] h-3 rounded-full overflow-hidden">
                <div 
                  className="bg-[#484880] h-full rounded-full"
                  style={{ width: `${progressPercent}%` }}
                />
              </div>
              <span className="text-white text-xl font-medium shrink-0">$10K</span>
            </div>
            
            <p className="text-gray-500 text-[17px]">
              ${remainingVolume.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} left to unlock this feature
            </p>
          </div>

          <hr className="border-[#1f1f26] mb-6" />

          <p className="text-gray-500 text-[17px] leading-relaxed max-w-md">
            Activate a referral code to get an 8% fee discount for lifetime in their trading volume. <br/>
            <a href="#" className="text-[#3b82f6] hover:underline italic">Learn more.</a>
          </p>
        </div>

        {/* Right Section */}
        <div className="space-y-4 lg:pl-8 lg:pt-4">
          
          <div className="bg-[#15151c] rounded-2xl p-7 hover:bg-[#1a1a22] transition-colors">
            <h3 className="text-[20px] font-semibold text-white mb-2 tracking-tight">Create and share a referral link</h3>
            <p className="text-[#848494] leading-relaxed text-[16px]">
              When a new user is onboarded with your code, they become your active referral.
            </p>
          </div>

          <div className="bg-[#15151c] rounded-2xl p-7 hover:bg-[#1a1a22] transition-colors">
            <h3 className="text-[20px] font-semibold text-white mb-2 tracking-tight">Gift fee discount to your referrals</h3>
            <p className="text-[#848494] leading-relaxed text-[16px]">
              Your referrals get a 8% discount on fee for lifetime in their trading volume.
            </p>
          </div>

          <div className="bg-[#15151c] rounded-2xl p-7 hover:bg-[#1a1a22] transition-colors">
            <h3 className="text-[20px] font-semibold text-white mb-2 tracking-tight">Earn Rewards</h3>
            <p className="text-[#848494] leading-relaxed text-[16px]">
              You receive upto 70% of the fee share generated by your referrals.
            </p>
          </div>

        </div>

      </div>
    </div>
  );
}
